### ISSUE TITLE
i/o time column always zero on overview screen

### ISSUE THREAD

**Issue by ribbles** [powa-team/powa#66]
Postgres 9.4
POWA 3.0.1

I/O timing column is always zero. It's even zero on the POWA demo site (http://demo-powa.dalibo.com/database/pgbench/overview/).

**Comment by rjuju** [comment]
Thanks a lot for the report!

Commit https://github.com/dalibo/powa-web/commit/a14a419fd8befcc027771f8b987551ba0d99a5a4 should fix the issue.

**Comment by dan-aksenov** [comment]
Hello. It seems to me this issue still exists in  powa 4.0.1. 
"I/O Time" and "Blocks Written" is always 0B on "General Overview" page.

Although select from pg_stat_kcache shows non null values in write field.

I see I've got emtpy result from:
`powa=# select * from pg_stat_statements where shared_blks_written > 0;`

But got non empty from:
`powa=# select * from pg_stat_kcache_detail where pg_stat_kcache_detail.writes > 0`

**Comment by rjuju** [comment]
Hello @dan-aksenov 

The root cause seems different in your case, as the UI seems to be correctly displaying what's being stored.

About IO timing, do you have track_io_timing activated?

Then, blocks written is indeed only shared block written, while pg_stat_kcache will see any write happening.  Maybe you have temporary files being written?  Another alternative would be if for some reason you have stored procedures that do writes on their own without using postgres infrastructure.  In such case only pg_stat_kcache would be able to report any activity.  Does any of those scenario applies to your case?

**Comment by rjuju** [comment]
I'll re close this issue and keep conversation at https://github.com/powa-team/powa/issues/137.
